In [1]:
import numpy as np

In [3]:
matrix_1 = np.array([[2, 4], [6, 7]])
print(matrix_1)

[[2 4]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix_2)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
matrix_2.shape

(3, 2)

In [7]:
## Creating matrices with random values

matrix_3 = np.random.rand(2, 3)
print(matrix_3)

[[0.04306171 0.58597025 0.31980797]
 [0.14364507 0.02569177 0.76945875]]


In [8]:
# Creating matrix with random integers

matrix_4 = np.random.randint(0, 10, size=(3, 3))
print(matrix_4)

[[7 9 6]
 [6 8 6]
 [3 4 3]]


In [9]:
# Matrix with all values as 1
matrix_ones = np.ones((3, 3))
print(matrix_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# Matrix with all values as 0
matrix_zeros = np.zeros((3, 3))
print(matrix_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Diagonal matrix
matrix_diagonal = np.diag([1, 2, 3, 4])
print(matrix_diagonal)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [13]:
# Identity matrix 

matrix_identity = np.identity(3)
print(matrix_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# Transponse of the matrix
matrix_1.T

array([[2, 6],
       [4, 7]])